name: Build FwSign

on:
  pull_request:
    branches: [ "main" ]
  # Allows to run this workflow from Actions tab
  workflow_dispatch:

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Ninja
      run: sudo apt -y install ninja-build

    - name: Checkout pull request HEAD
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Configure CMake
      working-directory: ${{github.workspace}}
      run: cmake --preset x64-debug-linux

    - name: Build
      working-directory: ${{github.workspace}}
      run: cmake --build --preset x64-debug-linux

    - name: Upload Linux build artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        name: linux-build-artifacts
        path: ${{github.workspace}}/build

  build_windows:
    runs-on: windows-latest

    steps:
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.10.0
      with:
        arch: amd64

    - name: Checkout pull request HEAD
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Configure CMake
      working-directory: ${{github.workspace}}
      run: cmake --preset x64-debug-windows

    - name: Build
      working-directory: ${{github.workspace}}
      run: cmake --build --preset x64-debug-windows

    - name: Upload Windows build artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        name: windows-build-artifacts
        path: ${{github.workspace}}\build
