name: Run FwSign unit tests

on:
  workflow_run:
    workflows: ["Build FwSign"]
    types:
      - completed

jobs:
  run_unit_tests_linux:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout pull request HEAD
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Download Linux build artifacts
      uses: actions/download-artifact@v3.0.0
      with:
        name: linux-build-artifacts
        path: ${{github.workspace}}/build

    - name: Relax build artifacts permissions
      run: sudo chmod 777 -R ${{github.workspace}}/build

    - name: Run Unit Tests
      working-directory: ${{github.workspace}}
      run: ctest --preset x64-debug-linux

  run_unit_tests_windows:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout pull request HEAD
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Download Windows build artifacts
      uses: actions/download-artifact@v3.0.0
      with:
        name: windows-build-artifacts
        path: ${{github.workspace}}\build

    - name: Run Unit Tests
      working-directory: ${{github.workspace}}
      run: ctest --preset x64-debug-windows
